#### Then Day 6 changes from an Excel task to a Pandas data cleaning task.

In [1]:
import pandas as pd

company = pd.read_csv("../data/raw/ai_company_adoption.csv")
industry = pd.read_csv("../data/raw/ai_industry_summary.csv")
country = pd.read_csv("../data/raw/country_ai_index.csv")

In [2]:
company_clean = company.copy()
industry_clean = industry.copy()
country_clean = country.copy()

In [4]:
company_clean.info()
print("------------------------------------")
industry_clean.info()
print("------------------------------------")
country_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 43 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   response_id                  150000 non-null  int64
 1   company_id                   150000 non-null  object
 2   survey_year                  150000 non-null  int64
 3   quarter                      150000 non-null  object
 4   country                      150000 non-null  object
 5   region                       150000 non-null  object
 6   industry                     150000 non-null  object
 7   company_size                 150000 non-null  object
 8   num_employees                150000 non-null  int64
 9   annual_revenue_usd_millions  150000 non-null  float64
 10  company_founding_year        150000 non-null  int64
 11  company_age                  150000 non-null  int64
 12  company_age_group            150000 non-null  object
 13  ai_adoption_rate             150000 non-null  float64
 14  ai_adoption_stage            150000 non-null  object
 15  years_using_ai               150000 non-null  int64
 16  ai_primary_tool              150000 non-null  object
 17  num_ai_tools_used            150000 non-null  int64
 18  ai_use_case                  150000 non-null  object
 19  ai_projects_active           150000 non-null  int64
 20  ai_training_hours            150000 non-null  float64
 21  ai_budget_percentage         150000 non-null  float64
 22  ai_maturity_score            150000 non-null  float64
 23  ai_failure_rate              150000 non-null  float64
 24  ai_investment_per_employee   150000 non-null  float64
 25  regulatory_compliance_score  150000 non-null  int64
 26  data_privacy_level           150000 non-null  object
 27  ai_ethics_committee          150000 non-null  object
 28  ai_risk_management_score     150000 non-null  int64
 29  remote_work_percentage       150000 non-null  float64
 30  employee_satisfaction_score  150000 non-null  float64
 31  task_automation_rate         150000 non-null  float64
 32  time_saved_per_week          150000 non-null  float64
 33  productivity_change_percent  150000 non-null  float64
 34  jobs_displaced               150000 non-null  int64
 35  jobs_created                 150000 non-null  int64
 36  reskilled_employees          150000 non-null  int64
 37  revenue_growth_percent       150000 non-null  float64
 38  cost_reduction_percent       150000 non-null  float64
 39  innovation_score             150000 non-null  int64
 40  customer_satisfaction        150000 non-null  float64
 41  survey_source                150000 non-null  object
 42  data_collection_method       150000 non-null  object
dtypes: float64(15), int64(14), object(14)
memory usage: 49.2+ MB
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 8 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   industry                         9 non-null      object
 1   avg_ai_adoption_rate             9 non-null      float64
 2   avg_productivity_change_percent  9 non-null      float64
 3   avg_ai_maturity_score            9 non-null      float64
 4   avg_ai_failure_rate              9 non-null      float64
 5   avg_jobs_displaced               9 non-null      float64
 6   avg_jobs_created                 9 non-null      float64
 7   avg_customer_satisfaction        9 non-null      float64
dtypes: float64(7), object(1)
memory usage: 708.0+ bytes
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   country                     30 non-null     object
 1   region                      30 non-null     object
 2   gdp_per_capita              30 non-null     float64
 3   internet_penetration        30 non-null     float64
 4   digital_maturity_index      30 non-null     float64
 5   country_ai_policy           30 non-null     object
 6   ai_patent_filings_2024      30 non-null     int64
 7   ai_researchers_per_million  30 non-null     float64
dtypes: float64(4), int64(1), object(3)
memory usage: 2.0+ KB

In [5]:
high_ai = company_clean[company_clean["ai_adoption_rate"] > 80]

high_ai.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
537,586,COMP-00037,2025,Q2,Nigeria,Africa,Technology,SME,587,470.58,...,22.97,51,59,81,11.84,8.14,72,7.29,WEF Survey,API Scrape
1393,1500,COMP-00094,2025,Q4,Australia,Oceania,Finance,Startup,32,38.00,...,21.12,2,3,5,2.44,6.77,66,6.17,McKinsey Report,Online Survey
3211,3440,COMP-00215,2026,Q4,Poland,Europe,Technology,Startup,91,37.51,...,24.06,7,9,18,18.99,10.58,74,6.56,WEF Survey,API Scrape
6036,6445,COMP-00403,2026,Q1,Thailand,Asia,Finance,Enterprise,19739,3027.18,...,21.83,1725,1635,2647,11.88,11.10,78,6.47,Internal Corporate Survey,Phone Interview
6583,7032,COMP-00440,2024,Q4,Indonesia,Asia,Retail,Startup,99,42.16,...,22.51,8,10,14,10.70,11.81,58,7.25,LinkedIn Poll,API Scrape

In [6]:
high_productivity = company_clean[
    company_clean["productivity_change_percent"] > 20
]

high_productivity.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
80,88,COMP-00006,2024,Q4,Chile,South America,Manufacturing,SME,572,348.58,...,23.04,49,30,36,13.17,3.41,51,6.57,LinkedIn Poll,Research Compilation
112,120,COMP-00008,2024,Q4,South Africa,Africa,Healthcare,Enterprise,18340,2630.56,...,21.47,1019,1079,2352,10.24,8.32,60,6.00,McKinsey Report,Research Compilation
217,238,COMP-00015,2026,Q2,Malaysia,Asia,Manufacturing,Enterprise,5642,7801.26,...,21.44,454,398,577,8.24,5.13,64,5.10,McKinsey Report,Online Survey
280,307,COMP-00020,2023,Q3,Netherlands,Europe,Retail,Enterprise,17538,3305.26,...,23.31,716,910,1475,12.32,8.18,58,5.63,McKinsey Report,Online Survey
288,315,COMP-00020,2025,Q3,Netherlands,Europe,Retail,Enterprise,17538,3305.26,...,20.04,1259,1636,1902,7.53,6.93,66,6.27,WEF Survey,Online Survey

In [7]:
high_maturity = company_clean[
    company_clean["ai_maturity_score"] > 75
]

high_maturity.head()

Empty DataFrame
Columns: [response_id, company_id, survey_year, quarter, country, region, industry, company_size, num_employees, annual_revenue_usd_millions, company_founding_year, company_age, company_age_group, ai_adoption_rate, ai_adoption_stage, years_using_ai, ai_primary_tool, num_ai_tools_used, ai_use_case, ai_projects_active, ai_training_hours, ai_budget_percentage, ai_maturity_score, ai_failure_rate, ai_investment_per_employee, regulatory_compliance_score, data_privacy_level, ai_ethics_committee, ai_risk_management_score, remote_work_percentage, employee_satisfaction_score, task_automation_rate, time_saved_per_week, productivity_change_percent, jobs_displaced, jobs_created, reskilled_employees, revenue_growth_percent, cost_reduction_percent, innovation_score, customer_satisfaction, survey_source, data_collection_method]
Index: []

[0 rows x 43 columns]

In [8]:
high_revenue = company_clean[
    company_clean["revenue_growth_percent"] > 15
]

high_revenue.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
51,55,COMP-00004,2024,Q3,Germany,Europe,Manufacturing,Startup,33,42.70,...,16.85,1,2,3,15.62,2.84,69,4.17,McKinsey Report,API Scrape
72,80,COMP-00005,2026,Q4,USA,North America,Finance,SME,519,454.35,...,13.92,11,20,26,15.64,1.12,52,7.87,LinkedIn Poll,API Scrape
85,93,COMP-00006,2026,Q1,Chile,South America,Manufacturing,SME,572,348.58,...,9.85,22,31,48,15.01,6.02,58,5.43,WEF Survey,Research Compilation
183,199,COMP-00013,2024,Q3,Thailand,Asia,Agriculture,SME,382,245.48,...,18.76,19,26,49,16.06,0.63,62,6.82,WEF Survey,API Scrape
206,226,COMP-00015,2023,Q2,Malaysia,Asia,Manufacturing,Enterprise,5642,7801.26,...,18.51,233,204,606,20.56,0.00,61,5.35,Internal Corporate Survey,Research Compilation

In [9]:
low_failure = company_clean[
    company_clean["ai_failure_rate"] < 20
]

low_failure.head()

,response_id,company_id,survey_year,quarter,country,region,industry,company_size,num_employees,annual_revenue_usd_millions,...,productivity_change_percent,jobs_displaced,jobs_created,reskilled_employees,revenue_growth_percent,cost_reduction_percent,innovation_score,customer_satisfaction,survey_source,data_collection_method
4,5,COMP-00001,2024,Q1,Italy,Europe,Education,Startup,57,48.31,...,6.32,2,3,6,11.30,9.02,43,6.31,McKinsey Report,Research Compilation
7,8,COMP-00001,2024,Q4,Italy,Europe,Education,Startup,57,48.31,...,5.72,2,4,5,10.72,3.95,64,3.55,Internal Corporate Survey,API Scrape
9,10,COMP-00001,2025,Q2,Italy,Europe,Education,Startup,57,48.31,...,12.31,3,4,5,11.45,5.83,55,5.71,WEF Survey,Online Survey
12,13,COMP-00001,2026,Q1,Italy,Europe,Education,Startup,57,48.31,...,15.46,7,4,4,3.51,12.03,63,7.19,McKinsey Report,Phone Interview
13,14,COMP-00001,2026,Q2,Italy,Europe,Education,Startup,57,48.31,...,11.81,2,3,4,4.31,9.75,52,5.22,LinkedIn Poll,Research Compilation

#### Dataset 2: ai_industry_summary.csv

In [20]:
high_ai_industry = industry_clean[
    industry_clean["avg_ai_adoption_rate"] > 80
]

high_ai_industry.head()

Empty DataFrame
Columns: [industry, avg_ai_adoption_rate, avg_productivity_change_percent, avg_ai_maturity_score, avg_ai_failure_rate, avg_jobs_displaced, avg_jobs_created, avg_customer_satisfaction]
Index: []

In [21]:
high_productivity_industry = industry_clean[
    industry_clean["avg_productivity_change_percent"] > 15
]

high_productivity_industry.head()

Empty DataFrame
Columns: [industry, avg_ai_adoption_rate, avg_productivity_change_percent, avg_ai_maturity_score, avg_ai_failure_rate, avg_jobs_displaced, avg_jobs_created, avg_customer_satisfaction]
Index: []

#### Conditional Formatting (Pandas Styler)
AI Adoption Rate

In [22]:
industry_clean.style.background_gradient(
    subset=["avg_ai_adoption_rate"],
    cmap="RdYlGn"
)

In [ ]:
#### Productivity Change

In [24]:
industry_clean.style.background_gradient(
    subset=["avg_productivity_change_percent"],
    cmap="RdYlGn"
)

### AI Maturity Score

In [25]:
industry_clean.style.background_gradient(
    subset=["avg_ai_maturity_score"],
    cmap="RdYlGn"
)

#### Dataset 3: country_ai_index.csv

In [26]:
high_digital = country_clean[
    country_clean["digital_maturity_index"] > 80
]

high_digital.head()

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
0,USA,North America,72596.06,92.10,87.14,Moderate,19952,417.69
1,Canada,North America,55834.08,96.78,84.67,Moderate,4233,393.62
2,Germany,Europe,54777.23,91.98,85.01,Strict,6475,369.58
3,UK,Europe,52827.64,91.41,83.85,Moderate,5612,345.98
4,France,Europe,47719.02,92.23,83.46,Moderate,4722,353.71

### 1. High Digital Maturity

In [27]:
high_digital = country_clean[
    country_clean["digital_maturity_index"] > 80
]

high_digital.head()

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
0,USA,North America,72596.06,92.10,87.14,Moderate,19952,417.69
1,Canada,North America,55834.08,96.78,84.67,Moderate,4233,393.62
2,Germany,Europe,54777.23,91.98,85.01,Strict,6475,369.58
3,UK,Europe,52827.64,91.41,83.85,Moderate,5612,345.98
4,France,Europe,47719.02,92.23,83.46,Moderate,4722,353.71

## 2. High AI Patent Filings

In [28]:
high_patents = country_clean[
    country_clean["ai_patent_filings_2024"] > 1000
]

high_patents.head()

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
0,USA,North America,72596.06,92.10,87.14,Moderate,19952,417.69
1,Canada,North America,55834.08,96.78,84.67,Moderate,4233,393.62
2,Germany,Europe,54777.23,91.98,85.01,Strict,6475,369.58
3,UK,Europe,52827.64,91.41,83.85,Moderate,5612,345.98
4,France,Europe,47719.02,92.23,83.46,Moderate,4722,353.71

#### 3. High AI Researchers

In [29]:
high_researchers = country_clean[
    country_clean["ai_researchers_per_million"] > 500
]

high_researchers.head()

,country,region,gdp_per_capita,internet_penetration,digital_maturity_index,country_ai_policy,ai_patent_filings_2024,ai_researchers_per_million
14,Singapore,Asia,72930.1,93.78,87.28,Moderate,2218,501.2

In [30]:
#### Conditional Formatting (Pandas Styler)

In [31]:
country_clean.style.background_gradient(
    subset=["digital_maturity_index"],
    cmap="RdYlGn"
)

In [32]:
#### AI Patent Filings

In [33]:
country_clean.style.background_gradient(
    subset=["ai_patent_filings_2024"],
    cmap="RdYlGn"
)

#### Task 2: Apply Cleaning Plan Using Pandas

In [40]:
company_clean["region"] = company_clean["region"].str.strip()
company_clean["survey_source"] = company_clean["survey_source"].str.strip()
company_clean[["region", "survey_source"]].head()

   region              survey_source
0  Europe                 Wef Survey
1  Europe            Mckinsey Report
2  Europe  Internal Corporate Survey
3  Europe  Internal Corporate Survey
4  Europe            Mckinsey Report

In [35]:
industry_clean["industry"] = industry_clean["industry"].str.strip()

In [36]:
country_clean["country"] = country_clean["country"].str.strip()
country_clean["region"] = country_clean["region"].str.strip()

### Harmonise Categories

In [37]:
company_clean["region"] = company_clean["region"].str.title()
company_clean["survey_source"] = company_clean["survey_source"].str.title()

In [38]:
industry_clean["industry"] = industry_clean["industry"].str.title()

In [39]:
country_clean["country"] = country_clean["country"].str.title()
country_clean["region"] = country_clean["region"].str.title()

In [41]:
company_clean["region"].unique()

array(['Europe', 'North America', 'South America', 'Asia', 'Africa',
       'Oceania'], dtype=object)

In [42]:
print(industry_clean["industry"].unique())

['Agriculture' 'Consulting' 'Education' 'Finance' 'Healthcare' 'Logistics'
 'Manufacturing' 'Retail' 'Technology']

In [43]:
print(country_clean["country"].unique())

print(country_clean["region"].unique())

['Usa' 'Canada' 'Germany' 'Uk' 'France' 'Netherlands' 'Sweden' 'Spain'
 'Italy' 'Poland' 'India' 'China' 'Japan' 'South Korea' 'Singapore'
 'Indonesia' 'Vietnam' 'Thailand' 'Philippines' 'Malaysia' 'Brazil'
 'Argentina' 'Chile' 'Colombia' 'South Africa' 'Nigeria' 'Kenya' 'Egypt'
 'Australia' 'New Zealand']
['North America' 'Europe' 'Asia' 'South America' 'Africa' 'Oceania']

In [44]:
print("Company:", company.shape[0], company_clean.shape[0])

print("Industry:", industry.shape[0], industry_clean.shape[0])

print("Country:", country.shape[0], country_clean.shape[0])

Company: 150000 150000
Industry: 0 9
Country: 30 30

In [45]:
company_clean.to_csv("../data/cleaned/ai_company_adoption_clean.csv", index=False)

industry_clean.to_csv("../data/cleaned/ai_industry_summary_clean.csv", index=False)

country_clean.to_csv("../data/cleaned/country_ai_index_clean.csv", index=False)

#### Validate and reconcile row counts against original file

In [46]:
# Compare row counts

print("Company Dataset")
print("Original Rows :", company.shape[0])
print("Cleaned Rows  :", company_clean.shape[0])

print("\nIndustry Dataset")
print("Original Rows :", industry.shape[0])
print("Cleaned Rows  :", industry_clean.shape[0])

print("\nCountry Dataset")
print("Original Rows :", country.shape[0])
print("Cleaned Rows  :", country_clean.shape[0])

Company Dataset
Original Rows : 150000
Cleaned Rows  : 150000

Industry Dataset
Original Rows : 0
Cleaned Rows  : 9

Country Dataset
Original Rows : 30
Cleaned Rows  : 30